# Generated by Django 3.2.10 on 2023-09-26 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_profile', models.BooleanField(default=True)),
                ('current_playing', models.BooleanField(default=True)),
                ('recently_played', models.BooleanField(default=True)),
                ('show_top_tracks', models.BooleanField(default=True)),
                ('show_top_artists', models.BooleanField(default=True)),
                ('show_top_genres', models.BooleanField(default=True)),
                ('show_top_albums', models.BooleanField(default=True)),
                ('show_streams', models.BooleanField(default=True)),
                ('show_streams_stats', models.BooleanField(default=True)),
                ('leaderboards', models.BooleanField(default=True)),
                ('show_friends', models.BooleanField(default=True)),
                ('show_connections', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
