# Generated by Django 3.2.10 on 2023-10-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacysettings',
            old_name='current_playing',
            new_name='show_current_playing',
        ),
        migrations.RenameField(
            model_name='privacysettings',
            old_name='leaderboards',
            new_name='show_leaderboards',
        ),
        migrations.RenameField(
            model_name='privacysettings',
            old_name='public_profile',
            new_name='show_public_profile',
        ),
        migrations.RenameField(
            model_name='privacysettings',
            old_name='recently_played',
            new_name='show_recently_played',
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
