# Generated by Django 3.2.10 on 2023-09-18 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0002_auto_20230917_1749"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifytoken",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
