# Generated by Django 3.2.10 on 2023-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0002_auto_20230921_1655"),
    ]

    operations = [
        migrations.AddField(
            model_name="topartists",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="topgenres",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="toptracks",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
