# Generated by Django 3.2.10 on 2023-09-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0003_spotifytoken_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifytoken",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
