# Generated by Django 3.2.10 on 2023-09-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0003_auto_20230921_1753"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="popularity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
