# Generated by Django 3.2.10 on 2023-09-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_artist_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='spotify_id',
            new_name='artist_id',
        ),
    ]
